import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Dashboardwrapper from "./Dashboardwrapper";

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "SwiftFlow",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.jpg",
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={inter.className}
      >
       <Dashboardwrapper> {children} </Dashboardwrapper>
      </body>
    </html>
  );
}
